### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by ajaleksa** [MangoCubes/cryptomator-ts#6]
Just wanted to ask if this project is meant to be in a public use domain. It is an awesome project that can be of a great help to many devs, but without the open source LICENSE it cannot be legally used. So just wanted to ask if it is meant for public use and if it is could you append it with a Open Source license of your choice.

Cheers :)

**Comment by MangoCubes** [comment]
Just noticed, and fixed. Thank you. :)
